class Job {
  final String id;
  final String title;
  final String company;
  final String description;
  final String location;
  final bool liked;

  Job({
    required this.id,
    required this.title,
    required this.company,
    required this.description,
    this.location = "台灣",
    this.liked = false,
  });

  factory Job.fromJson(Map<String, dynamic> j) {
    return Job(
      id: (j['id'] ?? j['ID'] ?? '0').toString(),
      title: j['title'] ?? j['OCCU_DESC'] ?? '未知職缺',
      company: j['company'] ?? j['COMPNAME'] ?? '未知企業',
      description: j['description'] ?? j['JOB_DETAIL'] ?? '暫無詳細說明',
      location: j['location'] ?? j['CITYNAME'] ?? '台灣',
      liked: j['liked'] ?? false,
    );
  }
}

final List<Job> allJobs = [
  // 科技/軟體業
  Job(id: "1", title: "AI 模型訓練實習生", company: "Google Taiwan", location: "台北市", description: "協助 LLM 繁體中文語料清洗與模型評估。"),
  Job(id: "2", title: "Frontend Engineering Intern", company: "Meta Taiwan", location: "遠端", description: "使用 React/Next.js 開發內部協作工具。"),
  Job(id: "3", title: "Flutter 行動開發實習生", company: "街口支付", location: "台北市", description: "參與支付模組與金融元件開發維護。"),
  Job(id: "4", title: "網路安全測試助理", company: "趨勢科技", location: "台北市", description: "協助自動化弱點掃描腳本編寫與系統監控。"),
  Job(id: "5", title: "Backend Developer Intern", company: "Line Taiwan", location: "台北市", description: "使用 Go/Java 進行高併發訊息處理優化。"),
  Job(id: "6", title: "雲端架構實習生", company: "Amazon AWS", location: "台北市", description: "協助客戶進行 AWS 雲端遷移與架構優化建議。"),
  Job(id: "7", title: "軟體測試實習生 (QA)", company: "Garena", location: "台北市", description: "負責遊戲平台功能測試與壓力測試腳本編寫。"),
  Job(id: "8", title: "數據平台實習生", company: "Snowflake", location: "台北市", description: "利用 SQL 進行大規模數據清洗與 ETL 流程優化。"),
  Job(id: "9", title: "UI/UX 設計實習生", company: "Pinkoi", location: "台北市", description: "參與電商網站改版設計與使用者行為訪談分析。"),
  Job(id: "10", title: "DevOps 實習工程師", company: "KKBOX", location: "台北市", description: "維護 CI/CD 流程與 Kubernetes 容器化部署環境。"),

  // 金融業
  Job(id: "11", title: "金融科技專案實習生", company: "國泰金控", location: "台北市", description: "參與數位銀行新功能定義與市場競品分析。"),
  Job(id: "12", title: "量化交易分析實習生", company: "元大證券", location: "台北市", description: "利用 Python 進行股市歷史數據分析與策略回測。"),
  Job(id: "13", title: "區塊鏈開發實習生", company: "MaiCoin", location: "台北市", description: "協助智能合約審核與去中心化錢包 API 介接。"),
  Job(id: "14", title: "保險科技(InsureTech)助理", company: "富邦人壽", location: "台北市", description: "協助推動數位投保流程優化與 UI 改進方案。"),
  Job(id: "15", title: "反洗錢(AML)數據助理", company: "玉山銀行", location: "新北", description: "利用資料探勘技術協助識別異常交易模式。"),

  // 硬體/半導體
  Job(id: "16", title: "韌體測試實習生", company: "台積電 (TSMC)", location: "新竹市", description: "協助晶圓生產監控系統的韌體自動化測試。"),
  Job(id: "17", title: "硬體研發助理", company: "聯發科技 (MediaTek)", location: "新竹市", description: "參與手機晶片訊號模擬與電路板佈局協助。"),
  Job(id: "18", title: "韌體開發實習生", company: "鴻海精密 (Foxconn)", location: "新北市", description: "參與電動車充電樁通訊協議開發與測試。"),
  Job(id: "19", title: "系統整合實習生", company: "華碩 (ASUS)", location: "台北市", description: "負責筆電系統 BIOS 更新測試與效能調優。"),
  Job(id: "20", title: "IC 設計輔助助理", company: "瑞昱半導體 (Realtek)", location: "新竹市", description: "協助網路晶片設計與相關驗證工作。"),

  // 電商/行銷/媒體
  Job(id: "21", title: "電商平台營運實習生", company: "蝦皮購物", location: "台北市", description: "參與雙 11 活動檔期規劃與後端訂單數據分析。"),
  Job(id: "22", title: "社群媒體企劃實習生", company: "Dcard", location: "台北市", description: "負責官方帳號內容創作、粉絲互動與熱度分析。"),
  Job(id: "23", title: "數位行銷分析助理", company: "Momo 購物網", location: "台北市", description: "協助管理 Google Ads 廣告帳戶與投放轉換率追蹤。"),
  Job(id: "24", title: "影音剪輯實習生", company: "Vogue Taiwan", location: "台北市", description: "負責時尚活動短片剪輯與社群限時動態設計。"),
  Job(id: "25", title: "產品管理(PM)助理", company: "PChome", location: "台北市", description: "撰寫產品功能需求規格書 (PRD) 與跨部門溝通。"),

  
  Job(id: "26", title: "Python 爬蟲實習生", company: "關鍵評論網", location: "台北市", description: "自動化抓取各類媒體新聞並進行關鍵字輿情分析。"),
  Job(id: "27", title: "產品設計助理", company: "Gogoro", location: "桃園市", description: "參與智慧電池交換站操作介面優化設計。"),
  Job(id: "28", title: "iOS 開發實習生", company: "17Live", location: "台北市", description: "協助直播軟體新功能開發與 Bug 修補。"),
  Job(id: "29", title: "大數據分析實習生", company: "Vpon 威朋", location: "台北市", description: "處理跨國行動數據並產出視覺化商業洞察報告。"),
  Job(id: "30", title: "App 安全測試助理", company: "奧義智慧", location: "台北市", description: "針對移動裝置進行滲透測試與安全漏洞回報。"),
  
  Job(id: "31", title: "HR 招募實習生", company: "LinkedIn Taiwan", location: "台北市", description: "協助篩選履歷與安排面試流程，優化求職者體驗。"),
  Job(id: "32", title: "自動化腳本開發", company: "研華科技", location: "台北市", description: "為工業電腦產線設計自動化測試腳本。"),
  Job(id: "33", title: "行銷數據工程師助理", company: "Appier", location: "台北市", description: "利用 AI 技術協助企業進行精準行銷數據處理。"),
  Job(id: "34", title: "客戶成功(CS)實習生", company: "SurveyCake", location: "台北市", description: "協助企業用戶解決問卷系統操作問題與產品回饋。"),
  Job(id: "35", title: "智慧醫療開發助理", company: "廣達電腦", location: "桃園市", description: "參與 AI 醫療影像辨識系統的數據標記與開發。"),
  Job(id: "36", title: "前端互動實習生", company: "Hahow 好學校", location: "遠端", description: "開發線上課程平台互動組件，提升學習體驗。"),
  Job(id: "37", title: "內容編輯實習生", company: "天下雜誌", location: "台北市", description: "負責專題報導資料蒐集、排版與初稿校對。"),
  Job(id: "38", title: "運籌管理實習生", company: "Lalamove", location: "台北市", description: "分析物流配送效率並提出路徑優化建議方案。"),
  Job(id: "39", title: "AR/VR 內容開發助理", company: "HTC Vive", location: "新北市", description: "協助開發元宇宙教育場景與 3D 模型介接。"),
  Job(id: "40", title: "永續發展(ESG)助理", company: "台泥", location: "台北市", description: "協助產出年度永續報告書與環境影響評估數據。"),
  Job(id: "41", title: "嵌入式系統實習生", company: "Garmin", location: "新北市", description: "參與運動手錶感測器驅動開發與電力管理測試。"),
  Job(id: "42", title: "財務分析實習生", company: "J.P. Morgan", location: "台北市", description: "協助產業研究分析與財務模型基礎建置。"),
  Job(id: "43", title: "法律科技助理", company: "Lawsnote", location: "台北市", description: "協助法律搜尋引擎的數據結構化與相關性優化。"),
  Job(id: "44", title: "旅遊產品開發助理", company: "KKday", location: "台北市", description: "參與跨國行程開發、定價策略與供應商管理。"),
  Job(id: "45", title: "分散式系統助理", company: "AWS Taiwan", location: "台北市", description: "研究雲端微服務架構並協助解決技術問題。"),
  Job(id: "46", title: "區塊鏈研究實習生", company: "幣安 (Binance)", location: "遠端", description: "研究 Web3 生態發展趨勢並撰寫研究報告。"),
  Job(id: "47", title: "人力資源數據助理", company: "104 人力銀行", location: "新北市", description: "分析就業市場趨勢並產出薪資報告統計。"),
  Job(id: "48", title: "智慧城市專案助理", company: "遠傳電信", location: "台北市", description: "參與 5G 智慧路燈與車聯網應用場景規劃。"),
  Job(id: "49", title: "機器學習實習生", company: "聯發科 AI 室", location: "新竹市", description: "負責邊緣運算晶片的語音辨識模型量化優化。"),
  Job(id: "50", title: "遊戲數值設計助理", company: "雷亞遊戲", location: "台北市", description: "協助調整遊戲關卡難度與數值平衡測試。"),

    Job(id: "60", title: "系統工程實習生", company: "Google Taiwan", location: "台北市", description: "協助內部系統維運與效能監控。"),
  Job(id: "61", title: "前端工程助理", company: "Meta Taiwan", location: "台北市", description: "協助前端介面開發與元件維護。"),
  Job(id: "62", title: "後端系統實習生", company: "Line Taiwan", location: "台北市", description: "參與後端服務開發與 API 測試。"),
  Job(id: "63", title: "雲端系統助理", company: "Amazon AWS", location: "台北市", description: "協助雲端服務架構測試與文件整理。"),
  Job(id: "64", title: "平台工程實習生", company: "Microsoft Taiwan", location: "台北市", description: "協助平台系統功能測試與改善。"),

  Job(id: "65", title: "資料分析實習生", company: "Appier", location: "台北市", description: "協助資料分析與模型效能追蹤。"),
  Job(id: "66", title: "資安研究助理", company: "趨勢科技", location: "台北市", description: "分析資安事件並整理研究資料。"),
  Job(id: "67", title: "滲透測試助理", company: "奧義智慧", location: "台北市", description: "協助系統滲透測試與漏洞回報。"),
  Job(id: "68", title: "產品平台實習生", company: "91APP", location: "台北市", description: "協助電商平台功能測試與優化。"),
  Job(id: "69", title: "互動前端實習生", company: "Hahow 好學校", location: "遠端", description: "開發課程平台互動功能。"),

  Job(id: "70", title: "製程資料實習生", company: "台積電", location: "新竹市", description: "協助製程資料分析與流程改善。"),
  Job(id: "71", title: "晶片驗證助理", company: "聯發科技", location: "新竹市", description: "協助晶片功能驗證與測試。"),
  Job(id: "72", title: "韌體測試實習生", company: "華碩", location: "台北市", description: "執行韌體功能測試與問題回報。"),
  Job(id: "73", title: "硬體驗證助理", company: "宏碁", location: "新北市", description: "協助硬體產品驗證與文件整理。"),
  Job(id: "74", title: "穿戴裝置實習生", company: "Garmin", location: "新北市", description: "參與穿戴裝置系統測試與資料分析。"),

  Job(id: "75", title: "平台營運實習生", company: "Shopee 蝦皮", location: "台北市", description: "協助平台營運數據分析。"),
  Job(id: "76", title: "產品管理助理", company: "PChome", location: "台北市", description: "協助產品需求整理與測試。"),
  Job(id: "77", title: "行銷分析實習生", company: "momo 購物網", location: "台北市", description: "分析行銷活動成效。"),
  Job(id: "78", title: "社群數據實習生", company: "Dcard", location: "台北市", description: "分析社群互動數據。"),
  Job(id: "79", title: "視覺設計助理", company: "Pinkoi", location: "台北市", description: "協助設計素材與版型整理。"),

  Job(id: "80", title: "金融系統實習生", company: "國泰金控", location: "台北市", description: "協助金融系統測試與資料分析。"),
  Job(id: "81", title: "數位銀行助理", company: "玉山銀行", location: "台北市", description: "支援數位金融服務測試。"),
  Job(id: "82", title: "市場資料實習生", company: "元大證券", location: "台北市", description: "整理市場交易資料。"),
  Job(id: "83", title: "保險系統助理", company: "富邦金控", location: "台北市", description: "協助保險系統流程測試。"),

  Job(id: "84", title: "通訊系統實習生", company: "中華電信", location: "台北市", description: "協助通訊系統測試與分析。"),
  Job(id: "85", title: "智慧應用助理", company: "遠傳電信", location: "台北市", description: "參與智慧應用專案測試。"),
  Job(id: "86", title: "能源管理實習生", company: "台達電", location: "桃園市", description: "協助能源管理系統測試。"),
  Job(id: "87", title: "工業系統助理", company: "研華科技", location: "新北市", description: "協助工業系統功能測試。"),

  Job(id: "88", title: "區塊鏈研究助理", company: "MaiCoin", location: "台北市", description: "協助區塊鏈應用研究。"),
  Job(id: "89", title: "旅遊系統實習生", company: "KKday", location: "台北市", description: "協助旅遊平台系統測試。"),
  Job(id: "90", title: "直播平台助理", company: "17LIVE", location: "台北市", description: "協助直播功能測試。"),
  Job(id: "91", title: "永續資料實習生", company: "台泥", location: "台北市", description: "協助 ESG 資料整理。"),

  Job(id: "92", title: "軟體測試實習生", company: "Google Taiwan", location: "台北市", description: "執行軟體功能測試與問題回報。"),
  Job(id: "93", title: "資料平台助理", company: "Meta Taiwan", location: "台北市", description: "協助資料平台維運。"),
  Job(id: "94", title: "後端服務實習生", company: "Line Taiwan", location: "台北市", description: "協助後端服務穩定性測試。"),
  Job(id: "95", title: "雲端架構助理", company: "Amazon AWS", location: "台北市", description: "支援雲端架構測試。"),

  Job(id: "96", title: "AI 應用實習生", company: "Microsoft Taiwan", location: "台北市", description: "協助 AI 應用測試與資料整理。"),
  Job(id: "97", title: "數據科學實習生", company: "Appier", location: "台北市", description: "分析模型資料並產出報告。"),
  Job(id: "98", title: "資安系統助理", company: "趨勢科技", location: "台北市", description: "協助資安系統測試。"),
  Job(id: "99", title: "資安工程實習生", company: "奧義智慧", location: "台北市", description: "參與資安專案測試。"),
    Job(id: "100", title: "系統測試實習生", company: "Garena", location: "台北市", description: "協助平台系統測試與問題回報。"),
  Job(id: "101", title: "資料工程助理", company: "Google Taiwan", location: "台北市", description: "協助資料處理流程與品質檢查。"),
  Job(id: "102", title: "前端工程實習生", company: "Meta Taiwan", location: "台北市", description: "協助前端功能模組開發。"),
  Job(id: "103", title: "後端工程助理", company: "Line Taiwan", location: "台北市", description: "支援後端系統維護與測試。"),
  Job(id: "104", title: "雲端系統實習生", company: "Amazon AWS", location: "台北市", description: "協助雲端服務測試與文件整理。"),

  Job(id: "105", title: "AI 研發助理", company: "Microsoft Taiwan", location: "台北市", description: "協助 AI 專案資料整理與測試。"),
  Job(id: "106", title: "資料分析實習生", company: "Appier", location: "台北市", description: "分析數據並產出視覺化報告。"),
  Job(id: "107", title: "資安測試實習生", company: "趨勢科技", location: "台北市", description: "執行資安測試與風險評估。"),
  Job(id: "108", title: "滲透測試助理", company: "奧義智慧", location: "台北市", description: "協助系統滲透測試作業。"),
  Job(id: "109", title: "產品工程實習生", company: "91APP", location: "台北市", description: "協助電商產品測試與優化。"),

  Job(id: "110", title: "互動介面實習生", company: "Hahow 好學校", location: "遠端", description: "開發線上學習互動介面。"),
  Job(id: "111", title: "製程資料助理", company: "台積電", location: "新竹市", description: "協助製程數據整理與分析。"),
  Job(id: "112", title: "晶片驗證實習生", company: "聯發科技", location: "新竹市", description: "協助晶片功能驗證流程。"),
  Job(id: "113", title: "韌體工程助理", company: "華碩", location: "台北市", description: "協助韌體系統測試。"),
  Job(id: "114", title: "硬體測試實習生", company: "宏碁", location: "新北市", description: "協助硬體功能測試。"),

  Job(id: "115", title: "嵌入式系統助理", company: "Garmin", location: "新北市", description: "協助嵌入式系統驗證。"),
  Job(id: "116", title: "營運資料實習生", company: "Shopee 蝦皮", location: "台北市", description: "分析平台營運數據。"),
  Job(id: "117", title: "產品助理(PM)", company: "PChome", location: "台北市", description: "協助產品需求整理。"),
  Job(id: "118", title: "行銷分析助理", company: "momo 購物網", location: "台北市", description: "協助行銷活動成效分析。"),
  Job(id: "119", title: "社群企劃實習生", company: "Dcard", location: "台北市", description: "協助社群內容規劃。"),

  Job(id: "120", title: "視覺設計實習生", company: "Pinkoi", location: "台北市", description: "支援平台視覺設計。"),
  Job(id: "121", title: "金融科技實習生", company: "國泰金控", location: "台北市", description: "協助金融科技專案測試。"),
  Job(id: "122", title: "數位銀行實習生", company: "玉山銀行", location: "台北市", description: "協助數位銀行服務驗證。"),
  Job(id: "123", title: "證券資訊助理", company: "元大證券", location: "台北市", description: "整理市場資訊數據。"),
  Job(id: "124", title: "保險系統實習生", company: "富邦金控", location: "台北市", description: "協助保險系統測試。"),

  Job(id: "125", title: "通訊工程實習生", company: "中華電信", location: "台北市", description: "協助通訊系統測試。"),
  Job(id: "126", title: "智慧應用實習生", company: "遠傳電信", location: "台北市", description: "參與智慧應用專案。"),
  Job(id: "127", title: "能源管理助理", company: "台達電", location: "桃園市", description: "協助能源系統資料整理。"),
  Job(id: "128", title: "工業系統實習生", company: "研華科技", location: "新北市", description: "協助工業系統測試。"),

  Job(id: "129", title: "區塊鏈研究實習生", company: "MaiCoin", location: "台北市", description: "研究區塊鏈技術應用。"),
  Job(id: "130", title: "旅遊平台實習生", company: "KKday", location: "台北市", description: "協助旅遊平台功能測試。"),
  Job(id: "131", title: "直播系統助理", company: "17LIVE", location: "台北市", description: "協助直播系統測試。"),
  Job(id: "132", title: "永續資料助理", company: "台泥", location: "台北市", description: "整理 ESG 相關資料。"),

  Job(id: "133", title: "軟體維運實習生", company: "Google Taiwan", location: "台北市", description: "協助系統維運與監控。"),
  Job(id: "134", title: "資料平台實習生", company: "Meta Taiwan", location: "台北市", description: "支援資料平台功能測試。"),
  Job(id: "135", title: "後端服務助理", company: "Line Taiwan", location: "台北市", description: "協助後端服務測試。"),
  Job(id: "136", title: "雲端技術助理", company: "Amazon AWS", location: "台北市", description: "支援雲端技術測試。"),

  Job(id: "137", title: "AI 系統實習生", company: "Microsoft Taiwan", location: "台北市", description: "協助 AI 系統測試。"),
  Job(id: "138", title: "資料科學助理", company: "Appier", location: "台北市", description: "支援資料分析專案。"),
  Job(id: "139", title: "資安分析實習生", company: "趨勢科技", location: "台北市", description: "分析資安事件資料。"),
  Job(id: "140", title: "資安工程助理", company: "奧義智慧", location: "台北市", description: "協助資安系統驗證。"),

  Job(id: "141", title: "產品測試實習生", company: "91APP", location: "台北市", description: "執行產品功能測試。"),
  Job(id: "142", title: "前端互動助理", company: "Hahow 好學校", location: "遠端", description: "支援互動功能開發。"),

  Job(id: "143", title: "製程工程實習生", company: "台積電", location: "新竹市", description: "協助製程工程資料整理。"),
  Job(id: "144", title: "IC 驗證助理", company: "聯發科技", location: "新竹市", description: "支援 IC 驗證測試。"),
  Job(id: "145", title: "韌體系統實習生", company: "華碩", location: "台北市", description: "協助韌體系統測試。"),
  Job(id: "146", title: "硬體工程助理", company: "宏碁", location: "新北市", description: "支援硬體工程測試。"),
  Job(id: "147", title: "穿戴裝置實習生", company: "Garmin", location: "新北市", description: "協助穿戴裝置系統測試。"),

  Job(id: "148", title: "平台營運助理", company: "Shopee 蝦皮", location: "台北市", description: "支援平台營運分析。"),
  Job(id: "149", title: "產品測試助理", company: "PChome", location: "台北市", description: "協助產品測試流程。"),
  Job(id: "150", title: "行銷系統實習生", company: "momo 購物網", location: "台北市", description: "協助行銷系統測試。"),
  Job(id: "151", title: "社群數據助理", company: "Dcard", location: "台北市", description: "分析社群數據。"),
  Job(id: "152", title: "視覺設計助理", company: "Pinkoi", location: "台北市", description: "支援視覺素材製作。"),

  Job(id: "153", title: "金融資料實習生", company: "國泰金控", location: "台北市", description: "整理金融資料。"),
  Job(id: "154", title: "銀行系統助理", company: "玉山銀行", location: "台北市", description: "支援銀行系統測試。"),
  Job(id: "155", title: "市場分析實習生", company: "元大證券", location: "台北市", description: "協助市場資料分析。"),
  Job(id: "156", title: "保險資訊助理", company: "富邦金控", location: "台北市", description: "整理保險系統資料。"),

  Job(id: "157", title: "通訊測試實習生", company: "中華電信", location: "台北市", description: "協助通訊測試作業。"),
  Job(id: "158", title: "智慧系統助理", company: "遠傳電信", location: "台北市", description: "支援智慧系統專案。"),
  Job(id: "159", title: "能源系統實習生", company: "台達電", location: "桃園市", description: "協助能源系統測試。"),
  Job(id: "160", title: "工業資料助理", company: "研華科技", location: "新北市", description: "整理工業系統資料。"),

  Job(id: "161", title: "區塊鏈工程實習生", company: "MaiCoin", location: "台北市", description: "協助區塊鏈系統測試。"),
  Job(id: "162", title: "旅遊系統助理", company: "KKday", location: "台北市", description: "支援旅遊平台系統。"),
  Job(id: "163", title: "直播功能實習生", company: "17LIVE", location: "台北市", description: "協助直播功能測試。"),
  Job(id: "164", title: "ESG 分析實習生", company: "台泥", location: "台北市", description: "協助 ESG 分析。"),

  Job(id: "165", title: "系統平台實習生", company: "Google Taiwan", location: "台北市", description: "協助平台系統測試。"),
  Job(id: "166", title: "資料整合助理", company: "Meta Taiwan", location: "台北市", description: "支援資料整合作業。"),
  Job(id: "167", title: "後端整合實習生", company: "Line Taiwan", location: "台北市", description: "協助後端系統整合。"),
  Job(id: "168", title: "雲端維運助理", company: "Amazon AWS", location: "台北市", description: "支援雲端維運。"),

  Job(id: "169", title: "AI 平台實習生", company: "Microsoft Taiwan", location: "台北市", description: "協助 AI 平台測試。"),
  Job(id: "170", title: "資料分析助理", company: "Appier", location: "台北市", description: "協助資料分析任務。"),
  Job(id: "171", title: "資安監控實習生", company: "趨勢科技", location: "台北市", description: "協助資安監控作業。"),
  Job(id: "172", title: "資安專案助理", company: "奧義智慧", location: "台北市", description: "支援資安專案。"),

  Job(id: "173", title: "產品系統實習生", company: "91APP", location: "台北市", description: "協助產品系統測試。"),
  Job(id: "174", title: "互動系統助理", company: "Hahow 好學校", location: "遠端", description: "支援互動系統開發。"),

  Job(id: "175", title: "製程測試實習生", company: "台積電", location: "新竹市", description: "協助製程測試。"),
  Job(id: "176", title: "IC 工程助理", company: "聯發科技", location: "新竹市", description: "支援 IC 工程作業。"),
  Job(id: "177", title: "韌體測試助理", company: "華碩", location: "台北市", description: "協助韌體測試。"),
  Job(id: "178", title: "硬體系統實習生", company: "宏碁", location: "新北市", description: "協助硬體系統驗證。"),
  Job(id: "179", title: "裝置測試助理", company: "Garmin", location: "新北市", description: "支援裝置測試。"),

  Job(id: "180", title: "平台分析實習生", company: "Shopee 蝦皮", location: "台北市", description: "分析平台使用數據。"),
  Job(id: "181", title: "產品資料助理", company: "PChome", location: "台北市", description: "整理產品資料。"),
  Job(id: "182", title: "行銷資料實習生", company: "momo 購物網", location: "台北市", description: "協助行銷資料分析。"),
  Job(id: "183", title: "社群系統助理", company: "Dcard", location: "台北市", description: "支援社群系統。"),
  Job(id: "184", title: "設計系統實習生", company: "Pinkoi", location: "台北市", description: "協助設計系統整理。"),

  Job(id: "185", title: "金融系統助理", company: "國泰金控", location: "台北市", description: "支援金融系統作業。"),
  Job(id: "186", title: "銀行資料實習生", company: "玉山銀行", location: "台北市", description: "整理銀行資料。"),
  Job(id: "187", title: "證券分析助理", company: "元大證券", location: "台北市", description: "協助證券分析。"),
  Job(id: "188", title: "保險資料助理", company: "富邦金控", location: "台北市", description: "整理保險資料。"),

  Job(id: "189", title: "通訊資料實習生", company: "中華電信", location: "台北市", description: "協助通訊資料整理。"),
  Job(id: "190", title: "智慧應用實習生", company: "遠傳電信", location: "台北市", description: "支援智慧應用測試。"),
  Job(id: "191", title: "能源資料助理", company: "台達電", location: "桃園市", description: "整理能源系統資料。"),
  Job(id: "192", title: "工業測試實習生", company: "研華科技", location: "新北市", description: "協助工業測試。"),

  Job(id: "193", title: "區塊鏈平台實習生", company: "MaiCoin", location: "台北市", description: "協助區塊鏈平台測試。"),
  Job(id: "194", title: "旅遊資料助理", company: "KKday", location: "台北市", description: "整理旅遊平台資料。"),
  Job(id: "195", title: "直播平台實習生", company: "17LIVE", location: "台北市", description: "協助直播平台測試。"),
   Job(id: "196", title: "平台系統實習生", company: "Google Taiwan", location: "台北市", description: "協助平台系統測試與文件整理。"),
  Job(id: "197", title: "資料分析助理", company: "Appier", location: "台北市", description: "協助資料分析與成效追蹤。"),
  Job(id: "198", title: "後端系統助理", company: "Line Taiwan", location: "台北市", description: "支援後端系統測試。"),
  Job(id: "199", title: "雲端技術實習生", company: "Amazon AWS", location: "台北市", description: "協助雲端技術驗證。"),
  Job(id: "200", title: "軟體工程助理", company: "Microsoft Taiwan", location: "台北市", description: "協助軟體功能測試與維護。"),


  Job(id: "201", title: "網頁前端開發實習生", company: "街口支付", location: "台北市", description: "協助維護支付系統的前端介面與效能優化。"),
  Job(id: "202", title: "Java 後端實習生", company: "玉山銀行", location: "新北市", description: "參與銀行核心系統的微服務架構開發與測試。"),
  Job(id: "203", title: "Python 數據爬蟲助理", company: "關鍵評論網", location: "遠端", description: "建立自動化爬蟲系統，抓取每日即時新聞數據。"),
  Job(id: "204", title: "iOS App 測試員", company: "17LIVE", location: "台北市", description: "負責直播 App 的新功能壓力測試與 Bug 回報。"),
  Job(id: "205", title: "Android 核心開發助理", company: "HTC", location: "新北市", description: "協助手機系統層級的效能調校與應用程式介接。"),
  Job(id: "206", title: "雲端資安監控實習生", company: "Palo Alto Networks", location: "台北市", description: "監控雲端流量異常並協助編寫自動化防護腳本。"),
  Job(id: "207", title: "機器學習影像辨識助理", company: "研華科技", location: "桃園市", description: "協助工業瑕疵檢測的 AI 影像模型標記與訓練。"),
  Job(id: "208", title: "UI 介面動效設計實習生", company: "Pinkoi", location: "台北市", description: "設計電商平台的轉場動畫與使用者體驗優化。"),
  Job(id: "209", title: "DevOps 自動化助理", company: "iKala", location: "台北市", description: "維護雲端伺服器的部署流程與 CI/CD 腳本開發。"),
  Job(id: "210", title: "資料工程實習生", company: "Vpon 威朋", location: "台北市", description: "處理大規模行動廣告數據，協助 ETL 流程建置。"),
  Job(id: "211", title: "Flutter 介面美化助理", company: "WeMo Scooter", location: "台北市", description: "優化共享機車 App 的地圖標記與租借流程 UI。"),
  Job(id: "212", title: "Golang 後端開發助理", company: "BitoPro", location: "台北市", description: "參與加密貨幣交易所的搓合引擎效能測試。"),
  Job(id: "213", title: "React Native 開發實習生", company: "Shopline", location: "遠端", description: "協助開發跨平台電商管理後台。"),
  Job(id: "214", title: "資料庫效能優化助理", company: "DBA 顧問公司", location: "台北市", description: "監控大型資料庫查詢效率並提供索引優化建議。"),
  Job(id: "215", title: "API 文件撰寫實習生", company: "Uber Taiwan", location: "台北市", description: "協助整理開發者文件與 API 範例程式碼。"),
  Job(id: "216", title: "自動化測試實習生", company: "趨勢科技", location: "台北市", description: "編寫 Selenium 腳本進行 Web 資安產品自動化測試。"),
  Job(id: "217", title: "產品分析實習生", company: "Dcard", location: "台北市", description: "利用數據分析使用者看板偏好與黏著度趨勢。"),
  Job(id: "218", title: "內容推薦演算法助理", company: "TikTok", location: "遠端", description: "協助調整推薦權重模型與 A/B Testing 數據追蹤。"),
  Job(id: "219", title: "PHP 後端維護助理", company: "露天拍賣", location: "台北市", description: "維護舊有電商系統功能並逐步轉移至新架構。"),
  Job(id: "220", title: "Node.js 串流開發實習生", company: "浪Live", location: "台北市", description: "協助直播間禮物特效與低延遲串流技術研發。"),
  Job(id: "221", title: "區塊鏈合約審查助理", company: "MaiCoin", location: "台北市", description: "協助檢查 Smart Contract 的邏輯漏洞。"),
  Job(id: "222", title: "SEO 搜尋優化實習生", company: "早安健康", location: "台北市", description: "優化健康內容文章架構以提升 Google 搜尋排名。"),
  Job(id: "223", title: "雲端儲存技術助理", company: "Synology 群暉", location: "新北市", description: "測試 NAS 雲端備份功能與跨裝置同步穩定性。"),
  Job(id: "224", title: "AR 濾鏡開發助理", company: "Snapchat", location: "遠端", description: "協助設計社群用擴增實境特效。"),
  Job(id: "225", title: "電子地圖資料分析師", company: "Garmin", location: "新北市", description: "分析全球路網資料並產出地圖圖資更新。"),
  Job(id: "226", title: "支付系統對帳助理", company: "綠界科技", location: "台北市", description: "協助開發自動化財務對帳工具。"),
  Job(id: "227", title: "AI 客服語料標記員", company: "國泰金控", location: "台北市", description: "針對對話機器人進行語意分類與回覆精準度校正。"),
  Job(id: "228", title: "Vue.js 前端實習生", company: "電玩通", location: "台北市", description: "維護遊戲新聞資訊站的前端介面。"),
  Job(id: "229", title: "大數據集群維護助理", company: "緯創軟體", location: "台北市", description: "協助維護 Hadoop 與 Spark 的運算集群穩定性。"),
  Job(id: "230", title: "資訊安全官助理", company: "星展銀行", location: "台北市", description: "協助執行員工資安演練與郵件過濾測試。"),
  Job(id: "231", title: "嵌入式瀏覽器助理", company: "Opera", location: "台北市", description: "測試瀏覽器在低效能裝置上的載入速度。"),
  Job(id: "232", title: "社群 API 介接實習生", company: "Accupass", location: "台北市", description: "開發整合社群帳號登入與票券自動推播功能。"),
  Job(id: "233", title: "前端效能調優助理", company: "蝦皮購物", location: "台北市", description: "優化電商大節日期間的首頁載入秒數。"),
  Job(id: "234", title: "雲端遊戲營運助理", company: "GeForce Now", location: "台北市", description: "監控伺服器延遲情形與連線穩定度。"),
  Job(id: "235", title: "區塊鏈節點維運員", company: "加密新創", location: "遠端", description: "確保公鏈節點 24 小時正常運作。"),
  Job(id: "236", title: "跨平台框架研究助理", company: "軟體研究社", location: "台中市", description: "比較 Flutter 與 KMP 的效能差異。"),
  Job(id: "237", title: "網站可存取性優化助理", company: "政府單位", location: "台北市", description: "協助優化無障礙網頁設計標準。"),
  Job(id: "238", title: "智慧家庭 App 實習生", company: "小米台灣", location: "台北市", description: "測試智慧家電與手機 App 的配對連動。"),
  Job(id: "239", title: "電子商務物流助理", company: "Momo 購物", location: "台北市", description: "分析物流倉儲數據優化出貨路徑。"),
  Job(id: "240", title: "遠端辦公工具研發助理", company: "Jitsi", location: "遠端", description: "優化視訊會議的語音壓縮演算法。"),
  Job(id: "241", title: "Python 科學計算助理", company: "中研院", location: "台北市", description: "協助處理天文觀測數據的計算與視覺化。"),
  Job(id: "242", title: "網路爬蟲資安實習生", company: "奧義智慧", location: "台北市", description: "分析惡意爬蟲行為與防範機制。"),
  Job(id: "243", title: "遊戲數值分析助理", company: "Rayark 雷亞", location: "台北市", description: "利用 SQL 分析遊戲內虛寶購買行為。"),
  Job(id: "244", title: "內容審查演算法助理", company: "Line Today", location: "台北市", description: "協助過濾假新聞與不當留言。"),
  Job(id: "245", title: "虛擬機器維護助理", company: "VMware", location: "台北市", description: "測試伺服器虛擬化後的穩定度表現。"),
  Job(id: "246", title: "智能運動數據分析助理", company: "Garmin", location: "新北市", description: "優化跑步與馬拉松數據的預測模型。"),
  Job(id: "247", title: "網站架構壓力測試助理", company: "電商新創", location: "台北市", description: "模擬高併發情境下的網站承受能力。"),
  Job(id: "248", title: "智慧城市感測器助理", company: "遠傳", location: "台北市", description: "分析智慧路燈的故障率與報修數據。"),
  Job(id: "249", title: "雲端計費系統實習生", company: "AWS", location: "台北市", description: "協助優化雲端資源計費的數據彙整流程。"),
  Job(id: "250", title: "軟體專案經理助理", company: "Microsoft", location: "台北市", description: "協助追蹤軟體開發進度與撰寫需求手冊。"),

  // --- 251 至 350 筆：製造業與半導體 (節選範例，請按此規律補齊) ---
  Job(id: "251", title: "晶片設計助理", company: "台積電", location: "新竹市", description: "協助進行晶片物理層設計規格整理。"),
  Job(id: "252", title: "製程控制實習生", company: "聯發科技", location: "新竹市", description: "監控生產線數據並回報異常參數。"),
  Job(id: "253", title: "硬體測試助手", company: "華碩", location: "台北市", description: "協助筆電散熱效能的壓力測試。"),
  Job(id: "254", title: "電路板佈局實習生", company: "宏碁", location: "新北市", description: "協助 PCB 零件擺放位置優化設計。"),
  Job(id: "255", title: "5G 通訊測試助理", company: "鴻海", location: "新北市", description: "測試通訊模組在不同環境下的訊號強度。"),
  Job(id: "256", title: "自動化設備助理", company: "研華", location: "台北市", description: "維護產線上的機械手臂控制程式。"),
  Job(id: "257", title: "材料分析實習生", company: "日月光", location: "高雄市", description: "協助分析封裝材料的耐熱性質。"),
  Job(id: "258", title: "IC 封裝測試助理", company: "力成科技", location: "新竹縣", description: "執行晶片封裝後的良率統計。"),
  Job(id: "259", title: "顯示面板開發助理", company: "友達光電", location: "台中市", description: "協助 OLED 螢幕色彩校正測試。"),
  Job(id: "260", title: "嵌入式韌體助理", company: "瑞昱", location: "新竹市", description: "協助網路晶片韌體 Bug 修復。"),

  Job(id: "261", title: "類比電路實習生", company: "聯詠科技", location: "新竹市", description: "協助驅動 IC 模擬與數據整理。"),
  Job(id: "262", title: "前端測試助理", company: "Yahoo Taiwan", location: "台北市", description: "維護門戶網站前端組件測試。"),
  Job(id: "263", title: "資料庫維護實習生", company: "Oracle Taiwan", location: "台北市", description: "協助 SQL 指令優化與備份管理。"),
  Job(id: "264", title: "App 安全研究助理", company: "奧義智慧", location: "台北市", description: "分析 App 漏洞並撰寫測試報告。"),
  Job(id: "265", title: "智慧家電軟體助理", company: "LG Electronics", location: "台北市", description: "測試家電連網功能與穩定性。"),
  Job(id: "266", title: "演算法測試實習生", company: "Appier", location: "台北市", description: "協助 AI 模型預測結果的比對。"),
  Job(id: "267", title: "硬體研發實習生", company: "技嘉科技", location: "新北市", description: "協助主機板電路測試與除錯。"),
  Job(id: "268", title: "雲端儲存實習生", company: "Synology", location: "新北市", description: "測試 NAS 系統檔案備份效能。"),
  Job(id: "269", title: "Linux 核心實習生", company: "Canonical", location: "遠端", description: "協助 Ubuntu 系統功能測試。"),
  Job(id: "270", title: "IC 設計數據助理", company: "奇景光電", location: "台南市", description: "整理晶片設計規格與實驗數據。"),
  Job(id: "271", title: "電子地圖維護助理", company: "TomTom", location: "台北市", description: "協助圖資更新與路徑數據分析。"),
  Job(id: "272", title: "網頁開發實習生", company: "104 人力銀行", location: "新北市", description: "協助招募系統前端介面維護。"),
  Job(id: "273", title: "網路維運實習生", company: "是方電訊", location: "台北市", description: "協助機房流量監控與異常排除。"),
  Job(id: "274", title: "光電研發助理", company: "群創光電", location: "台南市", description: "協助顯示面板光學性質測試。"),
  Job(id: "275", title: "韌體更新測試員", company: "Logitech", location: "新竹市", description: "測試滑鼠與鍵盤韌體更新穩定性。"),
  Job(id: "276", title: "數位訊號處理助理", company: "瑞昱半導體", location: "新竹市", description: "協助音訊晶片訊號測試。"),
  Job(id: "277", title: "視覺算法實習生", company: "訊連科技", location: "新北市", description: "協助人臉辨識模型資料標記。"),
  Job(id: "278", title: "雲端服務測試員", company: "Akamai", location: "台北市", description: "監控 CDN 節點連線速度。"),
  Job(id: "279", title: "資安弱點掃描助理", company: "PwC Taiwan", location: "台北市", description: "協助客戶系統執行弱點掃描。"),
  Job(id: "280", title: "機器學習實習生", company: "台經院", location: "台北市", description: "協助經濟數據預測模型建立。"),
  Job(id: "281", title: "物聯網平台助理", company: "光寶科技", location: "台北市", description: "協助物聯網感測器數據接接。"),
  Job(id: "282", title: "智慧駕駛研究助理", company: "工研院", location: "新竹縣", description: "協助自動駕駛系統路測數據分析。"),
  Job(id: "283", title: "分散式系統實習生", company: "區塊鏈新創", location: "台北市", description: "研究去中心化存儲協議。"),
  Job(id: "284", title: "晶圓包裝助理", company: "艾克爾", location: "桃園市", description: "協助晶圓封裝產線資料紀錄。"),
  Job(id: "285", title: "軟體本地化助理", company: "Microsoft", location: "遠端", description: "協助軟體繁體中文介面翻譯校對。"),
  Job(id: "286", title: "自動化腳本實習生", company: "研華科技", location: "台北市", description: "撰寫產線自動化測試腳本。"),
  Job(id: "287", title: "工業相機助理", company: "海康威視", location: "台北市", description: "協助工業相機參數調優。"),
  Job(id: "288", title: "電信核心網助理", company: "台灣大哥大", location: "台北市", description: "協助 5G 核心網設備維運。"),
  Job(id: "289", title: "手機射頻實習生", company: "OPPO Taiwan", location: "台北市", description: "協助手機訊號發射強度測試。"),
  Job(id: "290", title: "智慧手錶軟體助理", company: "Garmin", location: "新北市", description: "測試手錶應用程式介面邏輯。"),
  Job(id: "291", title: "遊戲引擎實習生", company: "Unity Taiwan", location: "台北市", description: "協助開發遊戲範例場景。"),
  Job(id: "292", title: "資料視覺化助理", company: "Tableau Taiwan", location: "台北市", description: "協助製作商業情報儀表板。"),
  Job(id: "293", title: "高效能運算助理", company: "NVIDIA", location: "台北市", description: "協助 GPU 運算伺服器效能測試。"),
  Job(id: "294", title: "資安合規助理", company: "KPMG Taiwan", location: "台北市", description: "協助 ISO 27001 文件整理。"),
  Job(id: "295", title: "網路爬蟲開發助理", company: "數據公司", location: "台北市", description: "開發電商商品價格爬蟲。"),
  Job(id: "296", title: "智慧城市硬體助理", company: "中興保全", location: "台北市", description: "測試智慧門鎖通訊功能。"),
  Job(id: "297", title: "生物資訊實習生", company: "基因公司", location: "台北市", description: "協助分析去氧核糖核酸序列數據。"),
  Job(id: "298", title: "混合實境助理", company: "HTC Vive", location: "新北市", description: "協助虛擬實境手勢辨識測試。"),
  Job(id: "299", title: "電力電子實習生", company: "台達電", location: "桃園市", description: "協助變壓器效能模擬與測試。"),
  Job(id: "300", title: "產品驗證實習生", company: "Sony Taiwan", location: "台北市", description: "協助影音產品上市前功能驗證。"),
  Job(id: "301", title: "IC 設計助理", company: "聯發科", location: "新竹市", description: "協助 IC 佈局資料整理。"),
  Job(id: "302", title: "晶圓測試助理", company: "台積電", location: "新竹市", description: "執行晶圓良率初步檢測。"),
  Job(id: "303", title: "筆電機構助理", company: "華碩", location: "台北市", description: "協助筆電外殼結構強度測試。"),
  Job(id: "304", title: "散熱模組助理", company: "微星", location: "新北市", description: "協助顯示卡散熱效能評估。"),
  Job(id: "305", title: "行動裝置開發助理", company: "宏碁", location: "台北市", description: "協助平板電腦軟體功能測試。"),
  Job(id: "306", title: "儲存系統實習生", company: "群暉", location: "新北市", description: "協助 DSM 系統穩定性測試。"),
  Job(id: "307", title: "網路通訊實習生", company: "瑞昱", location: "新竹市", description: "執行乙太網路晶片功能測試。"),
  Job(id: "308", title: "自動化生產助理", company: "研華", location: "台北市", description: "執行工業 4.0 產線數據採集。"),
  Job(id: "309", title: "伺服器硬體助理", company: "廣達", location: "桃園市", description: "執行伺服器主機板上電測試。"),
  Job(id: "310", title: "消費電子開發助理", company: "鴻海", location: "新北市", description: "協助電子產品組裝流程優化。"),
  Job(id: "311", title: "通訊晶片實習生", company: "聯詠", location: "新竹市", description: "協助無線通訊協定模擬。"),
  Job(id: "312", title: "系統單晶片助理", company: "創意電子", location: "新竹市", description: "協助 SoC 設計流程自動化。"),
  Job(id: "313", title: "電源管理實習生", company: "立錡科技", location: "新竹縣", description: "執行電源 IC 負載測試。"),
  Job(id: "314", title: "封裝技術助理", company: "日月光", location: "高雄市", description: "協助封裝良率異常原因分析。"),
  Job(id: "315", title: "測試工程實習生", company: "京元電子", location: "苗栗縣", description: "協助測試機台參數設定與監控。"),
  Job(id: "316", title: "記憶體測試助理", company: "華邦電子", location: "台中市", description: "協助快閃記憶體數據可靠性測試。"),
  Job(id: "317", title: "光通訊助理", company: "聯亞光電", location: "台南市", description: "協助雷射晶圓特性量測。"),
  Job(id: "318", title: "板卡設計實習生", company: "撼訊科技", location: "新北市", description: "協助顯示卡佈線資料整理。"),
  Job(id: "319", title: "光電顯示助理", company: "友達光電", location: "台中市", description: "執行面板色準度自動化校正。"),
  Job(id: "320", title: "電子零件測試助理", company: "國巨", location: "高雄市", description: "協助被動元件可靠度實驗。"),
  Job(id: "321", title: "車用系統實習生", company: "華創車電", location: "新北市", description: "協助車機介面與 App 連動測試。"),
  Job(id: "322", title: "航太系統助理", company: "漢翔", location: "台中市", description: "協助飛機零件結構數據整理。"),
  Job(id: "323", title: "太陽能開發助理", company: "茂迪", location: "台南市", description: "協助電池片轉換效率實驗。"),
  Job(id: "324", title: "機器人控制助理", company: "上銀科技", location: "台中市", description: "協助機械手臂路徑規劃測試。"),
  Job(id: "325", title: "工具機軟體實習生", company: "友嘉", location: "台中市", description: "協助 CNC 控制介面優化。"),
  Job(id: "326", title: "電子儀器測試助理", company: "致茂電子", location: "桃園市", description: "協助量測儀器精準度校準。"),
  Job(id: "327", title: "工業感測實習生", company: "台達電", location: "桃園市", description: "執行感測器訊號濾波處理。"),
  Job(id: "328", title: "硬碟技術助理", company: "Seagate", location: "台北市", description: "協助儲存媒介磁軌測試數據整理。"),
  Job(id: "329", title: "半導體材料助理", company: "環球晶", location: "新竹市", description: "協助矽晶圓純度檢驗流程。"),
  Job(id: "330", title: "微控制器實習生", company: "盛群半導體", location: "新竹市", description: "協助 MCU 範例程式編寫。"),
  Job(id: "331", title: "音訊電路助理", company: "美律實業", location: "台中市", description: "執行耳機聲學曲線量測。"),
  Job(id: "332", title: "熱傳導開發助理", company: "雙鴻科技", location: "新北市", description: "協助散熱管傳導效率實驗。"),
  Job(id: "333", title: "工業顯示器助理", company: "凌華科技", location: "新北市", description: "執行強固型螢幕耐衝擊測試。"),
  Job(id: "334", title: "無人機系統實習生", company: "雷虎科技", location: "台中市", description: "協助飛行控制系統參數調整。"),
  Job(id: "335", title: "電動車驅動助理", company: "東元電機", location: "台北市", description: "協助馬達控制變頻器測試。"),
  Job(id: "336", title: "感測晶片實習生", company: "原相科技", location: "新竹市", description: "執行影像感測器動態偵測測試。"),
  Job(id: "337", title: "光學鏡頭助理", company: "大立光", location: "台中市", description: "協助鏡片模具自動化檢測。"),
  Job(id: "338", title: "光學感測助理", company: "玉晶光", location: "台中市", description: "協助手機鏡頭模組組裝測試。"),
  Job(id: "339", title: "通訊射頻實習生", company: "穩懋半導體", location: "桃園市", description: "協助功率放大器特性量測。"),
  Job(id: "340", title: "無線模組助理", company: "正文科技", location: "新竹縣", description: "執行 Wi-Fi 6 路由器吞吐量測試。"),
  Job(id: "341", title: "路由器開發助理", company: "智邦科技", location: "新竹市", description: "協助網路交換器軟體版本更新。"),
  Job(id: "342", title: "數位家電實習生", company: "聲寶", location: "桃園市", description: "協助智慧冰箱面板功能測試。"),
  Job(id: "343", title: "廚房家電助理", company: "大同", location: "台北市", description: "執行電鍋溫控系統精準度測試。"),
  Job(id: "344", title: "智慧空調助理", company: "日立", location: "台北市", description: "協助空調遙控 App 通訊測試。"),
  Job(id: "345", title: "光碟儲存實習生", company: "錸德", location: "新竹縣", description: "協助長效儲存光碟讀取實驗。"),
  Job(id: "346", title: "電池管理系統助理", company: "新普科技", location: "新竹縣", description: "執行筆電電池充放電循環測試。"),
  Job(id: "347", title: "連接器實習生", company: "貿聯", location: "新北市", description: "協助高速傳輸線訊號衰減測試。"),
  Job(id: "348", title: "軟性電路板助理", company: "臻鼎", location: "桃園市", description: "協助 FPC 電路板彎折壽命測試。"),
  Job(id: "349", title: "電路保護實習生", company: "興勤電子", location: "高雄市", description: "協助壓敏電阻突波電流測試。"),
  Job(id: "350", title: "感測應用助理", company: "矽創電子", location: "新竹縣", description: "執行顯示驅動 IC 整合感測測試。"),

    Job(id: "351", title: "數位金融分析助理", company: "國泰金控", location: "台北市", description: "分析數位銀行 App 的使用者路徑。"),
  Job(id: "352", title: "行銷數據分析師助理", company: "蝦皮購物", location: "台北市", description: "計算促銷活動的 ROI 與點擊率。"),
  Job(id: "353", title: "社群小編實習生", company: "PChome", location: "台北市", description: "負責官方臉書粉絲團的貼文撰寫。"),
  Job(id: "354", title: "保險理賠自動化助理", company: "富邦金控", location: "台北市", description: "協助測試 AI 理賠審核系統。"),
  Job(id: "355", title: "證券交易資料員", company: "元大證券", location: "台北市", description: "整理每日市場交易量統計報表。"),
Job(id: "356", title: "支付平台營運助理", company: "Line Pay", location: "台北市", description: "協助商家對帳流程與數據紀錄。"),
  Job(id: "357", title: "數位行銷實習生", company: "Dcard", location: "台北市", description: "協助社群活動推廣與文案撰寫。"),
  Job(id: "358", title: "客戶關係助理", company: "國泰金控", location: "台北市", description: "協助處理數位銀行用戶意見回饋。"),
  Job(id: "359", title: "電子商務助理", company: "蝦皮購物", location: "台北市", description: "協助管理賣家後台功能說明文件。"),
  Job(id: "360", title: "行銷數據實習生", company: "Pinkoi", location: "台北市", description: "整理電商節慶活動轉化率報表。"),
  Job(id: "361", title: "媒體公關實習生", company: "奧美", location: "台北市", description: "協助新聞稿發布與媒體連繫。"),
  Job(id: "362", title: "內容企劃實習生", company: "天下雜誌", location: "台北市", description: "協助數位專題資料蒐集與整理。"),
  Job(id: "363", title: "市場研究助理", company: "尼爾森", location: "台北市", description: "協助零售通路銷售數據清洗。"),
  Job(id: "364", title: "廣告投放實習生", company: "Appier", location: "台北市", description: "協助管理數位廣告 A/B 測試。"),
  Job(id: "365", title: "供應鏈管理助理", company: "Lalamove", location: "台北市", description: "協助分析司機配送時程與熱點。"),
  Job(id: "366", title: "人力資源實習生", company: "104 人力銀行", location: "新北市", description: "協助篩選求職者履歷與安排面試。"),
  Job(id: "367", title: "視覺設計助理", company: "Hahow", location: "遠端", description: "製作線上課程宣傳網頁素材。"),
  Job(id: "368", title: "產品營運實習生", company: "Garena", location: "台北市", description: "監控遊戲伺服器狀態與社群反饋。"),
  Job(id: "369", title: "數位支付實習生", company: "街口支付", location: "台北市", description: "協助推廣線下通路條碼支付應用。"),
  Job(id: "370", title: "電商倉儲助理", company: "PChome", location: "台北市", description: "優化自動化倉儲系統揀貨邏輯。"),
  Job(id: "371", title: "金融法務實習生", company: "玉山銀行", location: "台北市", description: "協助整理法規遵循查檢表。"),
  Job(id: "372", title: "智能客服實習生", company: "富邦銀行", location: "台北市", description: "標記語音辨識錯誤並進行校正。"),
  Job(id: "373", title: "旅遊產品助理", company: "KKday", location: "遠端", description: "協助上架全球各地旅遊行程資訊。"),
  Job(id: "374", title: "短影音企劃實習生", company: "TikTok", location: "台北市", description: "協助創作者活動策劃與執行。"),
  Job(id: "375", title: "財務稽核助理", company: "安永", location: "台北市", description: "協助整理上市櫃公司查帳底稿。"),
  Job(id: "376", title: "品牌行銷實習生", company: "Uniqlo", location: "台北市", description: "執行店舖促銷活動成效追蹤。"),
  Job(id: "377", title: "數據洞察助理", company: "Vpon", location: "台北市", description: "製作行動數據趨勢視覺化圖表。"),
  Job(id: "378", title: "新創加速器助理", company: "AppWorks", location: "台北市", description: "協助聯繫新創團隊與安排媒合會。"),
  Job(id: "379", title: "遊戲數值實習生", company: "雷亞遊戲", location: "台北市", description: "協助平衡遊戲內物品屬性數值。"),
  Job(id: "380", title: "線上客服助理", company: "Shopee", location: "台北市", description: "解決買賣家申訴與退款爭議。"),
  Job(id: "381", title: "證券分析實習生", company: "元大證券", location: "台北市", description: "蒐集各產業財務報告數據。"),
  Job(id: "382", title: "物流排程助理", company: "嘉里大榮", location: "新北市", description: "協助優化貨車配送路徑順序。"),
  Job(id: "383", title: "零售數據助理", company: "全聯", location: "台北市", description: "分析生鮮產品銷量與庫存關係。"),
  Job(id: "384", title: "智慧醫療助理", company: "廣達電腦", location: "桃園市", description: "協助標記醫學影像辨識數據。"),
  Job(id: "385", title: "數位轉型助理", company: "勤業眾信", location: "台北市", description: "協助客戶導入 ERP 系統測試。"),
  Job(id: "386", title: "跨國貿易實習生", company: "長榮海運", location: "桃園市", description: "整理國際貨櫃報關相關文件。"),
  Job(id: "387", title: "內容編輯助理", company: "關鍵評論網", location: "遠端", description: "協助整理新聞報導參考資料。"),
  Job(id: "388", title: "社群分析助理", company: "Qsearch", location: "台北市", description: "利用關鍵字分析網路熱門議題。"),
  Job(id: "389", title: "平台測試實習生", company: "91APP", location: "台北市", description: "執行電商 App 回歸測試。"),
  Job(id: "390", title: "智慧交通助理", company: "Gogoro", location: "桃園市", description: "協助換電站數據回傳異常排除。"),
  Job(id: "391", title: "財務會計實習生", company: "台積電", location: "新竹市", description: "協助成本計算與憑證核銷。"),
  Job(id: "392", title: "招募渠道助理", company: "LinkedIn", location: "台北市", description: "維護企業徵才頁面與職缺刊登。"),
  Job(id: "393", title: "智慧零售實習生", company: "統一超商", location: "台北市", description: "測試無人商店掃描結帳流程。"),
  Job(id: "394", title: "虛擬貨幣助理", company: "MaiCoin", location: "台北市", description: "執行虛擬貨幣實名制審核。"),
  Job(id: "395", title: "產品通路助理", company: "聯強國際", location: "台北市", description: "協助 3C 產品經銷商庫存管理。"),
  Job(id: "396", title: "能源管理實習生", company: "台達電", location: "桃園市", description: "協助收集儲能設備運行數據。"),
  Job(id: "397", title: "遊戲營運助理", company: "遊戲橘子", location: "新北市", description: "協助遊戲改版活動測試。"),
  Job(id: "398", title: "房地產分析助理", company: "信義房屋", location: "台北市", description: "協助整理內政部實價登錄數據。"),
  Job(id: "399", title: "飯店管理實習生", company: "晶華酒店", location: "台北市", description: "協助線上訂房系統數據整合。"),
  Job(id: "400", title: "雲端計費助理", company: "AWS", location: "台北市", description: "協助客戶雲端帳單分析。"),
  Job(id: "401", title: "數位金融助理", company: "中信銀行", location: "台北市", description: "協助網銀功能改版使用者測試。"),
  Job(id: "402", title: "證券商實習生", company: "凱基證券", location: "台北市", description: "整理每日融資融券數據報表。"),
  Job(id: "403", title: "銀行內控助理", company: "兆豐銀行", location: "台北市", description: "協助整理反洗錢申報資料。"),
  Job(id: "404", title: "保險精算實習生", company: "國泰人壽", location: "台北市", description: "協助計算保單死亡率統計數據。"),
  Job(id: "405", title: "財富管理助理", company: "渣打銀行", location: "台北市", description: "協助整理基金產品說明文件。"),
  Job(id: "406", title: "投資銀行實習生", company: "高盛", location: "台北市", description: "蒐集併購案市場分析資料。"),
  Job(id: "407", title: "投信產品助理", company: "野村投信", location: "台北市", description: "更新 ETF 每日淨值數據。"),
  Job(id: "408", title: "產險核保助理", company: "新光產險", location: "台北市", description: "協助審核車險投保基本資料。"),
  Job(id: "409", title: "期貨交易實習生", company: "元大期貨", location: "台北市", description: "監控盤後交易系統運行。"),
  Job(id: "410", title: "信用卡營運助理", company: "台新銀行", location: "台北市", description: "協助信用卡開卡流程數據整理。"),
  Job(id: "411", title: "電子支付助理", company: "悠遊卡公司", location: "台北市", description: "協助分析悠遊付通路交易額。"),
  Job(id: "412", title: "創投研究助理", company: "之初創投", location: "台北市", description: "蒐集東南亞新創市場趨勢。"),
  Job(id: "413", title: "信貸審核實習生", company: "王道銀行", location: "台北市", description: "協助初步篩選信貸申請文件。"),
  Job(id: "414", title: "供應鏈金融助理", company: "永豐銀行", location: "台北市", description: "協助整理企業用戶融資額度資料。"),
  Job(id: "415", title: "量化模型助理", company: "自營商", location: "台北市", description: "使用 Python 進行交易策略回測。"),
  Job(id: "416", title: "理財規畫助理", company: "台北富邦", location: "台北市", description: "協助製作個人財務分析報告。"),
  Job(id: "417", title: "數位資產實習生", company: "幣安", location: "遠端", description: "研究全球 Web3 監管法規變化。"),
  Job(id: "418", title: "融資租賃助理", company: "中租控股", location: "台北市", description: "協助機械設備租賃合約管理。"),
  Job(id: "419", title: "票券交易實習生", company: "國際票券", location: "台北市", description: "整理商業本票買賣成交數據。"),
  Job(id: "420", title: "外匯操作助理", company: "第一銀行", location: "台北市", description: "協助整理每日各幣別收盤匯率。"),
  Job(id: "421", title: "不動產融資助理", company: "土地銀行", location: "台北市", description: "協助整理土建融案件審核表。"),
  Job(id: "422", title: "區塊鏈開發助理", company: "XREX", location: "台北市", description: "協助跨境支付結算系統測試。"),
  Job(id: "423", title: "反欺詐分析實習生", company: "Grab", location: "遠端", description: "識別異常訂單與信用卡盜刷。"),
  Job(id: "424", title: "金融大數據助理", company: "SAS", location: "台北市", description: "協助開發銀行端風險預警模型。"),
  Job(id: "425", title: "退休金規畫助理", company: "三商美邦", location: "台北市", description: "計算各年齡層退休缺口數據。"),
  Job(id: "426", title: "行銷公關實習生", company: "台灣賓士", location: "台北市", description: "協助新車發表會媒體聯繫。"),
  Job(id: "427", title: "精品行銷助理", company: "LVMH", location: "台北市", description: "執行精品專櫃活動數據回報。"),
  Job(id: "428", title: "連鎖通路營運實習生", company: "全家", location: "台北市", description: "協助店舖點數兌換機制分析。"),
  Job(id: "429", title: "快速消費品實習生", company: "寶潔", location: "台北市", description: "協助洗髮精品牌市佔率調查。"),
  Job(id: "430", title: "飲料市場行銷助理", company: "可口可樂", location: "台北市", description: "執行超商促銷活動佈置核對。"),
  Job(id: "431", title: "電商活動企劃實習生", company: "momo", location: "台北市", description: "參與「雙 12」活動網頁設計討論。"),
  Job(id: "432", title: "影音串流營運助理", company: "Netflix", location: "遠端", description: "監控各類型影集完看率數據。"),
  Job(id: "433", title: "線上教育行銷助理", company: "Hahow", location: "台北市", description: "協助管理課程推廣廣告帳戶。"),
  Job(id: "434", title: "餐飲數據助理", company: "瓦城", location: "新北市", description: "分析各分店尖峰時段翻桌率。"),
  Job(id: "435", title: "美妝品牌實習生", company: "萊雅", location: "台北市", description: "協助新品發表會 VIP 名單整理。"),
  Job(id: "436", title: "快時尚營運助理", company: "Zara", location: "台北市", description: "協助管理每週庫存更新報表。"),
  Job(id: "437", title: "百貨周年慶助理", company: "新光三越", location: "台北市", description: "執行周年慶期間點數統計。"),
  Job(id: "438", title: "連鎖餐飲企劃實習生", company: "麥當勞", location: "台北市", description: "參與快樂兒童餐贈品企劃。"),
  Job(id: "439", title: "超商鲜食助理", company: "萊爾富", location: "台北市", description: "整理飯糰類產品每日報廢率。"),
  Job(id: "440", title: "咖啡連鎖營運實習生", company: "星巴克", location: "台北市", description: "分析星禮程會員消費偏好。"),
  Job(id: "441", title: "運動品牌行銷助理", company: "Nike", location: "台北市", description: "協助安排簽約運動員採訪。"),
  Job(id: "442", title: "手機行銷實習生", company: "三星", location: "台北市", description: "執行摺疊手機校園推廣專案。"),
  Job(id: "443", title: "電競行銷助理", company: "雷蛇", location: "台北市", description: "協助管理電競比賽贊助流程。"),
  Job(id: "444", title: "旅遊電商助理", company: "Trip.com", location: "台北市", description: "執行跨國機票價格競爭分析。"),
  Job(id: "445", title: "飯店訂房行銷實習生", company: "Agoda", location: "遠端", description: "協助優化熱門景點飯店描述。"),
  Job(id: "446", title: "影城營運助理", company: "威秀影城", location: "台北市", description: "分析週末熱門強檔電影排片量。"),
  Job(id: "447", title: "藝文活動企劃助理", company: "兩廳院", location: "台北市", description: "協助推廣年度音樂節票務。"),
  Job(id: "448", title: "健身房數據實習生", company: "World Gym", location: "台北市", description: "整理會員入會率與退費原因。"),
  Job(id: "449", title: "藥妝通路助理", company: "屈臣氏", location: "台北市", description: "執行醫美品牌專區銷售分析。"),
  Job(id: "450", title: "汽車租賃助理",company: "和運租車", location: "台北市", description: "負責客戶租車手續辦理、車輛調度及行政支援。"),
    
  Job(id: "451", title: "永續發展報告助理", company: "台泥", location: "台北市", description: "蒐集碳排數據協助撰寫 ESG 報告。"),
  Job(id: "452", title: "教育科技內容助理", company: "Hahow", location: "遠端", description: "協助課程影片的字幕校對與排版。"),
  Job(id: "453", title: "物流配送優化助理", company: "Lalamove", location: "台北市", description: "協助分析配送路徑與司機效率。"),
  Job(id: "454", title: "AR 導覽開發助理", company: "故宮博物院", location: "台北市", description: "開發文物導覽的擴增實境展示功能。"),
  Job(id: "455", title: "智慧紡織開發助理", company: "聚陽", location: "台北市", description: "協助感測元件與服飾整合測試。"),
  Job(id: "456", title: "永續農業助理", company: "農業新創", location: "台中市", description: "監控智慧溫室內光照與溼度數據。"),
  Job(id: "457", title: "航空營運實習生", company: "星宇航空", location: "台北市", description: "協助分析航線載客率與燃油成本。"),
  Job(id: "458", title: "共享單車運調助理", company: "YouBike", location: "台北市", description: "分析各站點車輛需求熱點數據。"),
  Job(id: "459", title: "循環經濟助理", company: "循環台灣", location: "台北市", description: "蒐集廢棄物再利用的市場案例。"),
  Job(id: "460", title: "寵物科技實習生", company: "Furbo", location: "台北市", description: "測試寵物攝影機自動投幣功能。"),
  Job(id: "461", title: "數位健康實習生", company: "iHealth", location: "台北市", description: "協助整理遠距醫療服務流程。"),
  Job(id: "462", title: "空間設計助理", company: "特力屋", location: "台北市", description: "協助 3D 虛擬家裝渲染圖製作。"),
  Job(id: "463", title: "聲學工程實習生", company: "美律實業", location: "台中市", description: "執行藍牙耳機主動降噪效能測試。"),
  Job(id: "464", title: "無人機載具助理", company: "雷虎科技", location: "台中市", description: "協助無人機地面控制站軟體維護。"),
  Job(id: "465", title: "智慧物流開發助理", company: "嘉里大榮", location: "台北市", description: "協助自動化分揀機數據連動測試。"),
  Job(id: "466", title: "電動車軟體助理", company: "MIH 聯盟", location: "台北市", description: "協助電動車開放平台 SDK 文件維護。"),
  Job(id: "467", title: "虛擬網紅(VTuber)助理", company: "媒體公司", location: "台北市", description: "協助動作捕捉系統設定與校正。"),
  Job(id: "468", title: "數位策展實習生", company: "北美館", location: "台北市", description: "協助數位藝術展互動裝置架設。"),
  Job(id: "469", title: "水資源管理助理", company: "環境工程", location: "台北市", description: "監控水處理廠感測器數據報表。"),
  Job(id: "470", title: "社會企業營運助理", company: "社企流", location: "台北市", description: "協助整理各類社會企業影響力指標。"),
  Job(id: "471", title: "機器學習實習生", company: "耐能人工智慧", location: "台北市", description: "協助量化 AI 模型以適配終端晶片。"),
  Job(id: "472", title: "電子書營運助理", company: "Readmoo", location: "台北市", description: "協助處理 EPUB 格式書籍上架測試。"),
  Job(id: "473", title: "音訊合成助理", company: "訊連科技", location: "新北市", description: "協助語音合成(TTS)資料庫錄製標記。"),
  Job(id: "474", title: "智慧量測實習生", company: "致茂電子", location: "桃園市", description: "協助量測機台自動化介面優化。"),
  Job(id: "475", title: "再生能源研究助理", company: "沃旭能源", location: "台北市", description: "分析離岸風機發電量與風速相關性。"),
  Job(id: "476", title: "數位隱私助理", company: "趨勢科技", location: "台北市", description: "研究歐盟 GDPR 法規對 App 的影響。"),
  Job(id: "477", title: "虛擬實境互動實習生", company: "Meta", location: "台北市", description: "開發 VR 社交平台內的小遊戲互動。"),
  Job(id: "478", title: "金融區塊鏈助理", company: "國泰世華", location: "台北市", description: "測試企業端區塊鏈融資存證系統。"),
  Job(id: "479", title: "智慧語音測試助理", company: "Amazon", location: "台北市", description: "測試 Alexa 的繁體中文語句理解力。"),
  Job(id: "480", title: "工業視覺實習生", company: "凌華科技", location: "新北市", description: "協助開發工業瑕疵辨識邊緣運算模組。"),
  Job(id: "481", title: "數據標記助理", company: "Appen", location: "遠端", description: "針對自駕車街景圖進行物件框選標記。"),
  Job(id: "482", title: "內容農場識別助理", company: "Google", location: "台北市", description: "協助過濾搜尋引擎中的低質量網頁。"),
  Job(id: "483", title: "虛擬貨幣法遵助理", company: "幣託", location: "台北市", description: "審核用戶身分證件進行 KYC 驗證。"),
  Job(id: "484", title: "智慧燈桿專案助理", company: "光寶", location: "台北市", description: "協助收集 5G 燈桿上的微氣象站數據。"),
  Job(id: "485", title: "網路安全實習生", company: "勤業眾信", location: "台北市", description: "執行模擬駭客攻擊(紅隊演練)的數據紀錄。"),
  Job(id: "486", title: "機器人導覽助理", company: "軟銀", location: "台北市", description: "測試 Pepper 機器人在展覽館的對話流。"),
  Job(id: "487", title: "數位地圖實習生", company: "HERE Technologies", location: "台北市", description: "更新台北市交通標誌異動數據。"),
  Job(id: "488", title: "基因定序助理", company: "華聯生技", location: "新竹市", description: "執行生物晶片掃描後的數據比對。"),
  Job(id: "489", title: "跨境物流助理", company: "DHL", location: "桃園市", description: "分析跨國空運時程與報關通關效率。"),
  Job(id: "490", title: "電商廣告助理", company: "Google Ads", location: "台北市", description: "協助中小企業客戶優化關鍵字出價。"),
  Job(id: "491", title: "影音壓制實習生", company: "CatchPlay", location: "台北市", description: "協助 4K 影片格式轉換與多國音軌壓制。"),
  Job(id: "492", title: "擴增實境展示助理", company: "宇萌數位", location: "台北市", description: "製作展場用 AR 互動網頁。"),
  Job(id: "493", title: "智慧園區助理", company: "研華", location: "桃園市", description: "監控智慧園區內的電能使用熱點圖。"),
  Job(id: "494", title: "自駕車傳感器助理", company: "英特爾", location: "台北市", description: "協助光學雷達(LiDAR)數據清洗。"),
  Job(id: "495", title: "線上支付資安助理", company: "Visa", location: "台北市", description: "協助分析 Tokenization 交易成功率。"),
  Job(id: "496", title: "區塊鏈遊戲實習生", company: "GameFi 新創", location: "遠端", description: "協助測試 NFT 虛擬寶物發放流程。"),
  Job(id: "497", title: "衛星通訊助理", company: "低軌衛星新創", location: "台北市", description: "協助處理衛星地面站信號接收數據。"),
  Job(id: "498", title: "數位雙生(Digital Twin)助理", company: "達梭系統", location: "台北市", description: "協助建立工廠設備的虛擬模型鏡像。"),
  Job(id: "499", title: "人工智慧倫理助理", company: "學術研究機構", location: "台北市", description: "蒐集 AI 生成內容的偏見案例並分類。"),
  Job(id: "500", title: "智慧城市專案實習生", company: "遠傳電信", location: "台北市", description: "參與 5G 智慧路燈數據分析與應用。"),
];